version: '3.8'

services:
  # Vue.js Frontend (Development)
  frontend-dev:
    build:
      context: ./src/frontend/vue
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend/vue:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
      - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID:-demo-client-id}
      - VITE_AZURE_TENANT_ID=${VITE_AZURE_TENANT_ID:-common}
      - VITE_AZURE_SUBSCRIPTION_ID=${VITE_AZURE_SUBSCRIPTION_ID:-demo-subscription}
    profiles:
      - dev
    networks:
      - brutus-network

  # Vue.js Frontend (Production)
  frontend-prod:
    build:
      context: ./src/frontend/vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    profiles:
      - prod
    networks:
      - brutus-network
    depends_on:
      - backend-go

  # SvelteKit Frontend (Development)
  svelte-dev:
    build:
      context: ./src/frontend/svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5173"
    volumes:
      - ./src/frontend/svelte:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
      - VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID:-demo-client-id}
      - VITE_AZURE_TENANT_ID=${VITE_AZURE_TENANT_ID:-common}
      - VITE_AZURE_SUBSCRIPTION_ID=${VITE_AZURE_SUBSCRIPTION_ID:-demo-subscription}
    profiles:
      - dev
      - svelte
    networks:
      - brutus-network

  # SvelteKit Frontend (Production)
  svelte-prod:
    build:
      context: ./src/frontend/svelte
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    profiles:
      - prod
      - svelte
    networks:
      - brutus-network

  # Go Backend
  backend-go:
    build:
      context: ./src/backend/go/az
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    profiles:
      - backend
      - prod
      - dev
    networks:
      - brutus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python Backend
  backend-python:
    build:
      context: ./src/backend/python/az
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    profiles:
      - backend
      - python
    networks:
      - brutus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TypeScript Backend
  backend-typescript:
    build:
      context: ./src/backend/typescript/az
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    profiles:
      - backend
      - typescript
    networks:
      - brutus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Load Balancer (for multiple backends)
  nginx-lb:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
    profiles:
      - loadbalancer
    networks:
      - brutus-network
    depends_on:
      - backend-go
      - backend-python
      - backend-typescript

networks:
  brutus-network:
    driver: bridge

volumes:
  node_modules_vue:
  node_modules_svelte: