
services:
  # Vue.js Frontend (Development)
  frontend-dev:
    build:
      context: ./src/frontend/vue
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend/vue:/app
      - /app/node_modules
    profiles:
      - dev
    networks:
      - brutus-network

  # Vue.js Frontend (Production)
  frontend-prod:
    build:
      context: ./src/frontend/vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    profiles:
      - prod
    networks:
      - brutus-network
    depends_on:
      - backend-go


  # Go Backend
  backend-go:
    build:
      context: ./src/backend/go/az
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    profiles:
      - backend
      - prod
      - dev
    networks:
      - brutus-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3



networks:
  brutus-network:
    driver: bridge

volumes:
  node_modules_vue: